version: '3.8'

services:
  admin:
    build:
      context: ./admin
      dockerfile: Dockerfile
    ports:
      - "3001:80"
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    restart: always

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
    restart: always
